spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/test_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 20
